language: python

python:
  - "3.4"
  
  
addons:
  apt:
    packages:
      - python3-pyqt5

install:
 - pip install cx_freeze==4.3.3
 - pip install libyaz0
 - pip install sarclib

script:
 - python build.py
